inner join 
SELECT c.C_NAME ,c.DEMAND, p.P_NAME, t.TRANSACTION_DATE, t.TOTAL_AMOUNT FROM CUSTOMER c JOIN TRANSACTION t ON c.C_ID = t.C_ID JOIN PRODUCT p ON p.P_ID = t.P_ID;
left join
SELECT c.C_ID, c.C_NAME, c.DEMAND FROM CUSTOMER c LEFT JOIN "TRANSACTION" t ON c.C_ID = t.C_ID WHERE t.T_ID IS not NULL;
right join
SELECT p.P_ID, p.P_NAME FROM TRANSACTION t RIGHT JOIN PRODUCT p ON t.P_ID = p.P_ID WHERE t.T_ID IS not NULL;
SELECT p.P_ID, p.P_NAME FROM TRANSACTION t RIGHT JOIN PRODUCT p ON t.P_ID = p.P_ID WHERE t.T_ID IS  NULL;
full outer join
SELECT c.C_NAME, t.T_ID FROM CUSTOMER c FULL OUTER JOIN TRANSACTION t ON c.C_ID = t.C_ID;
