rank function
SELECT c.C_NAME, SUM(t.TOTAL_AMOUNT) AS total_spent, RANK() OVER (ORDER BY SUM(t.TOTAL_AMOUNT) DESC) AS spend_rank FROM CUSTOMER c JOIN "TRANSACTION" t ON c.C_ID = t.C_ID GROUP BY c.C_NAME;
SELECT C_NAME, DEMAND, DENSE_RANK() OVER (ORDER BY DEMAND DESC) AS demand_rank FROM CUSTOMER; 
aggregate window function
SELECT t.TRANSACTION_DATE, t.TOTAL_AMOUNT ,SUM(t.TOTAL_AMOUNT) OVER (ORDER BY t.TRANSACTION_DATE ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS running_total FROM "TRANSACTION" t ORDER BY t.TRANSACTION_DATE;
navigation function
SELECT t.TRANSACTION_DATE, t.TOTAL_AMOUNT, LAG(t.TOTAL_AMOUNT) OVER (ORDER BY t.TRANSACTION_DATE) AS previous_amount FROM "TRANSACTION" t ORDER BY t.TRANSACTION_DATE;
distribution function NTILE
SELECT c.C_NAME, SUM(t.TOTAL_AMOUNT) AS total, NTILE(4) OVER (ORDER BY SUM(t.TOTAL_AMOUNT) DESC) AS customer_quartile FROM CUSTOMER c JOIN "TRANSACTION" t ON c.C_ID = t.C_ID GROUP BY c.C_NAME ORDER BY total DESC;
